#!/usr/bin/env node
/* Phase one: the world as text, before it is ever drawn.
 *
 * Prints a seeded world running, so it can be tuned on evidence rather than
 * on intuition. Two views, and the gap between them is the whole design:
 *
 *   --truth   all sixteen bands, everything that happens
 *   --reader  three bands, one aggregate - what somebody actually gets
 *
 * Usage:
 *   node tools/sim_harness.mjs --seed dorada --days 3
 *   node tools/sim_harness.mjs --seed dorada --days 30 --summary
 *   node tools/sim_harness.mjs --seed dorada --reader --every 1 --days 1
 */

import { readFileSync } from 'node:fs';
import { createWorld, replay, step, applyAction, trace } from '../app/sim/engine.js';
import { bandLevels, alignment, isPeaking, nextConjunction, echoBand } from '../app/sim/world.js';
import { observe } from '../app/sim/instruments.js';

const argv = process.argv.slice(2);
const flag = (n) => argv.includes('--' + n);
const opt = (n, d) => {
  const i = argv.indexOf('--' + n);
  return i >= 0 && argv[i + 1] ? argv[i + 1] : d;
};

const cfg = JSON.parse(readFileSync(new URL('../content/misterio/senal/sim.json', import.meta.url)));
const seed = opt('seed', 'dorada');
const days = Number(opt('days', 3));
const perDay = Math.round(1440 / cfg.tickMinutes);
const ticks = Math.round(days * perDay);
const every = Number(opt('every', flag('summary') ? 12 : 3));

const world = createWorld(cfg, seed);

/* ------------------------------------------------------------- reporting */

const RAMP = ' .:+*#@';
const cell = (v) => RAMP[Math.min(RAMP.length - 1, Math.max(0, Math.round(v * 5)))];
const hhmm = (t) => {
  const m = t * cfg.tickMinutes;
  return String(Math.floor(m / 1440)).padStart(2, '0') + 'd'
    + String(Math.floor((m % 1440) / 60)).padStart(2, '0') + ':'
    + String(m % 60).padStart(2, '0');
};

function truth() {
  console.log('THE WORLD  seed "' + seed + '"');
  console.log('  base period P   ' + world.P + ' ticks (' + (world.P * cfg.tickMinutes / 60).toFixed(1) + ' h)');
  console.log('  multiples       ' + world.mults.join(' '));
  console.log('  voice periods   ' + world.voices.map(v =>
    v.period + 't/' + (v.period * cfg.tickMinutes / 60) + 'h').join('  '));
  console.log('  home bands      ' + world.voices.map(v => v.home).join(' '));
  console.log('  grand cycle     ' + world.cycle + ' ticks ('
    + (world.cycle * cfg.tickMinutes / 1440).toFixed(2) + ' days)');
  console.log('  offset          ' + world.offset);
  console.log('  echo delay      ' + world.delay + ' ticks ('
    + (world.delay * cfg.tickMinutes / 60).toFixed(1) + ' h)  P-multiple? '
    + (world.delay % world.P === 0 ? 'YES - BUG' : 'no'));
  console.log('  band map        pi(b) = (' + world.map.mult + 'b + ' + world.map.add + ') mod ' + cfg.bands
    + '   e.g. 0->' + echoBand(world, 0) + ' 1->' + echoBand(world, 1) + ' 2->' + echoBand(world, 2));
  const day = world.voices.find(v => v.period * cfg.tickMinutes === 1440);
  console.log('  the daily voice ' + (day ? 'voice ' + day.id + ', period exactly 24 h' : 'NONE - BUG'));
  console.log('');
}

/* A scripted reader who plays the way the design assumes somebody will: read
   the coarse groups, point all three slots into the hottest one, ping inside
   it now and then. Deliberately not a blind script - a blind one cannot tell
   us whether the search loop works, only that it is possible to see nothing.
   Generated by running the world, so it reacts like a person would. */
function script() {
  const log = [];
  let s = replay(world, [], 0);
  const push = (a) => { log.push(a); s = applyAction(world, s, a); };

  for (let t = 1; t <= ticks; t++) {
    s = step(world, s);
    /* Every four hours, reconsider - but only move if there is nothing to
       stay for. A reader who has found a voice holds the band and waits for
       it to peak again, because two successive peaks is what a period is.
       Chasing the loudest group every four hours is what a reader does before
       they understand the instrument, and it is why they learn nothing. */
    if (t % 30 === 0) {
      const o = observe(world, s);
      const holding = Object.values(o.fine).some(v => v > world.cfg.humFloor * 1.5);
      if (!holding) {
        let hot = 0;
        o.coarse.forEach((v, g) => { if (v > o.coarse[hot]) hot = g; });
        const base = hot * o.coarseSize;
        push({ tick: t, kind: 'listen', bands: [base, base + 1, base + 2] });
      }
    }
    /* Probe the fourth band of that group - the one attention cannot reach. */
    if (t % 180 === 90 && s.charges > 0) {
      push({ tick: t, kind: 'ping', band: s.attention[0] + 3 });
    }
  }
  return log;
}

function waterfall(log, reader) {
  const head = '        ' + Array.from({ length: cfg.bands }, (_, b) => (b % 10)).join('');
  console.log(reader ? 'READER VIEW  (# watched, ? unwatched, coarse total at right)' : 'TRUTH');
  console.log(head + (reader ? '   coarse' : '   align  events'));

  let s = replay(world, log, 0);
  for (let t = 1; t <= ticks; t++) {
    s = step(world, s);
    for (const a of log) if (a.tick === s.tick) s = applyAction(world, s, a);

    const notable = s.events.filter(e => e.kind !== 'undamp');
    if (t % every !== 0 && !notable.length) continue;

    if (reader) {
      const o = observe(world, s);
      const row = Array.from({ length: cfg.bands }, (_, b) =>
        o.attention.includes(b) ? cell(o.fine[b]) : '·').join('');
      console.log(hhmm(t) + ' ' + row + '   ' + o.coarse.map(v => v.toFixed(2)).join(' ')
        + '  ' + String(o.charges) + '●'
        + notable.map(e => ' ' + e.kind + (e.band !== undefined ? ':' + e.band : '')).join(''));
    } else {
      const lv = bandLevels(world, s);
      const a = alignment(world, t);
      console.log(hhmm(t) + ' ' + lv.map(cell).join('') + '   ' + (a || ' ')
        + '     ' + notable.map(e =>
          e.kind + (e.band !== undefined ? ':' + e.band : '')
          + (e.kind === 'move' ? ' v' + e.voice + ' ' + e.from + '>' + e.to + '(' + e.why + ')' : '')).join(' '));
    }
  }
}

function summary(log) {
  const hist = new Array(world.voices.length + 1).fill(0);
  const conj = [];
  const moves = { shy: 0, ping: 0, damp: 0 };
  let echoes = 0, chargeMax = 0, held = 0, caught = 0;

  let s = replay(world, log, 0);
  for (let t = 1; t <= ticks; t++) {
    s = step(world, s);
    for (const a of log) if (a.tick === s.tick) s = applyAction(world, s, a);
    hist[alignment(world, t)]++;
    chargeMax = Math.max(chargeMax, s.charges);

    /* The two numbers that decide whether this is playable. `held` is how
       often a voice is sitting in a band the reader is listening to - do they
       have anything at all on screen. `caught` is how often one of those
       voices is actually peaking - do they ever see something happen. A world
       that scores low on the second is a world nobody comes back to. */
    const watching = world.voices.filter(v => s.attention.includes(s.bands[v.id]));
    if (watching.length) held++;
    if (watching.some(v => isPeaking(world, v, t))) caught++;
    for (const e of s.events) {
      if (e.kind === 'conjunction') conj.push(t);
      if (e.kind === 'echo') echoes++;
      if (e.kind === 'move') moves[e.why]++;
    }
  }

  console.log('OVER ' + days + ' DAYS (' + ticks + ' ticks)');
  console.log('  voices peaking together, share of ticks:');
  hist.forEach((n, k) => {
    const pct = n / ticks * 100;
    console.log('    ' + k + ' voices  ' + String(n).padStart(5) + '  '
      + pct.toFixed(2).padStart(6) + '%  ' + '#'.repeat(Math.round(pct / 2)));
  });
  console.log('  grand conjunctions  ' + conj.length + ' at ticks ' + conj.join(', '));
  console.log('  predicted next      ' + nextConjunction(world, 0) + ', then every ' + world.cycle);
  console.log('  echoes returned     ' + echoes);
  console.log('  voice relocations   shy ' + moves.shy + '  ping ' + moves.ping + '  damp ' + moves.damp);
  console.log('  charges never above ' + chargeMax + ' (cap ' + cfg.charges.max + ')');
  console.log('  reader had a voice in view   ' + (held / ticks * 100).toFixed(1) + '% of ticks');
  console.log('  reader saw one peaking       ' + (caught / ticks * 100).toFixed(1) + '% of ticks (live)');

  /* What actually matters: opening the console and looking at the waterfall.
     Live presence at a peak is nearly impossible by construction; reading one
     off the trace afterwards is the whole point of the instrument. */
  for (const win of [45, 180, 540]) {
    let peaks = 0, samples = 0;
    for (let t0 = win; t0 <= ticks; t0 += win) {
      samples++;
      const seq = trace(world, log, t0 - win, t0,
        (w, st) => w.voices.filter(v => st.attention.includes(st.bands[v.id]))
                           .some(v => isPeaking(w, v, st.tick)));
      let runs = 0;
      for (let i = 1; i < seq.length; i++) if (seq[i] && !seq[i - 1]) runs++;
      peaks += runs;
    }
    console.log('  peaks in a ' + String(win).padStart(3) + '-tick waterfall ('
      + String(win * cfg.tickMinutes / 60).padStart(2) + 'h)  '
      + (peaks / samples).toFixed(1) + ' on average');
  }
}

truth();
const log = script();
if (flag('summary')) summary(log);
else waterfall(log, flag('reader'));
